baseURL: https://wonderful-smoke-0948d1603.azurestaticapps.net/
languageCode: en-us
title: Ust Does Tech
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable Google Analytics
googleAnalytics: UA-204947579-1

# Enable Disqus forum
disqusShortname: ustdoes-tech

enableEmoji: true

params:
  #gitRepo: https://github.com/uoldfield/ust-blog
  enableBlogPost: true
  enableTOC: true
  env: production
  # title: UstDoes.Tech
  # profileMode:
  #       enabled: true
  #       imageUrl: https://github.com/UstDoesTech/ust-blog/blob/main/assets/images/Ust.png
  #       buttons:
  #         - name: Posts
  #           url: "/content/posts/"
  #         - name: Github
  #           url: "https://github.com/UstDoesTech"
  
  # cover:
  #   image: images/jordan2.jpg
  # socialIcons: # optional
  #   - name: "<platform>"
  #     url: "<link>"
  #   - name: "<platform 2>"
  #     url: "<link2>"
  background: images/jordan2.png
  logo:
    main: images/logo.png
    inverted: images/logo.png
    favicon: images/logo.png
  newsletter:
    enable: false
  
