baseURL: www.ustdoes.tech
languageCode: en-us
title: Ust Does Tech
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

params:
  gitRepo: https://github.com/uoldfield/ust-blog
  enableBlogPost: true
  enableTOC: true
