baseURL: https://wonderful-smoke-0948d1603.azurestaticapps.net/
languageCode: en-us
title: Ust Does Tech
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable Google Analytics
googleAnalytics: UA-204947579-1

# Enable Disqus forum
disqusShortname: ustdoes-tech

enableEmoji: true

params:
  #gitRepo: https://github.com/uoldfield/ust-blog
  enableBlogPost: true
  enableTOC: true
  background: images/jordan2.jpg
  logo:
    main: images/icon.png
    inverted: images/icon.png
    favicon: images/icon.png
  newsletter:
    enable: false
  
